### ISSUE TITLE
How to get column data if header contains the space?

### ISSUE THREAD

**Issue by crmrbls** [vlucas/sheetquery#13]
As mentioned in your README file, to find the data in the row is supposed like this.

```sheetQuery()
  .from('Transactions')
  .where((row) => row.Business.toLowerCase().includes('starbucks'))
  .updateRows((row) => {
    row.Category = 'Coffee Shops';
  });
```

I have the spreadsheet that linked into google form with built-in email respondent input but have no idea to get the row if the column header (like `Business` in that README file) is having the space in between the name (ex: `Email Address` is created with built-in google forms feature, and you can't really rename it because it was predetermined). I hope i can find the way out.

**Comment by vlucas** [comment]
If it contains a space, a dash, or any other special character, you just have to use array access notation instead:

```javascript
row['Email Address']
```
