### ISSUE TITLE
Incorrect getValues() and getRows() description

### ISSUE THREAD

**Issue by rubensa** [vlucas/sheetquery#19]
[getValues() description](https://github.com/vlucas/sheetquery/blob/main/dist/index.js#L62) says:

> Get values in sheet from current query + where condition

but the function [does not apply](https://github.com/vlucas/sheetquery/blob/main/dist/index.js#L65-L86) the [where](https://github.com/vlucas/sheetquery/blob/main/dist/index.js#L43) function.

[getRows() descrption](https://github.com/vlucas/sheetquery/blob/main/dist/index.js#L89) says:

> Return matching rows from sheet query

but it really calls `getValues()` and then [applies](https://github.com/vlucas/sheetquery/blob/main/dist/index.js#L95) the [where](https://github.com/vlucas/sheetquery/blob/main/dist/index.js#L43) condition.

**Comment by vlucas** [comment]
This feels like semantics. The end result is that rows are returned with the filter applied.

**Comment by rubensa** [comment]
But the getValues() description says that the where condition is applied but it is not.

And the getRows() doesn't say it applies the where but it does.

So it seems that the descriptions in the doc are like interchanged, isn't it?
