### ISSUE TITLE
SheetQuery cannot be found in G Script library.

### ISSUE THREAD

**Issue by Kalaiz** [vlucas/sheetquery#3]
I used the [script id provided in the repo's readme ](https://github.com/vlucas/sheetquery#:~:text=1pbpojxddhvevr6wqmr5tzksqtsw4qwdilcvkim6ukyvswkivwhppnhao)and was unable to find it. Am I doing something wrong?
![Screenshot from 2021-07-04 17-15-53](https://user-images.githubusercontent.com/44941115/124379799-aba3dc00-dceb-11eb-9bd3-acc33de6677b.png)

**Comment by vlucas** [comment]
Hmmm.. Does it work now?

Link: https://script.google.com/macros/library/d/1pbpOJxDDHVeVr6WQmR5TZKSqTsW4qwdIlcVKIM6UKYvswkivwHpPnHaO/5
