### ISSUE TITLE
[FEATURE REQUEST] Insert new row with primary key & auto increment

### ISSUE THREAD

**Issue by ps915** [vlucas/sheetquery#6]
First of all, thank you so much for this library.

I am wondering if you plan to add a feature like adding a new row of data with a primary key and auto increment like MySQL has. 

This would be an awesome feature and would complement your library. :)

**Comment by vlucas** [comment]
Maintaining an auto-increment key is outside of the scope of this library.

The intent of this library is to facilitate easy read/write access to Google Sheets, not to turn Google Sheets into a full blown relational database.

That said, it should be feasible to create a set of small functions to do this for you _using_ SheetQuery to read and write the data required.
