### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by everythingability** [vlucas/sheetquery#8]
Hi, 

I added the Library, all OK... but then when I run an "insert" function I get...

TypeError: sheetQuery is not a function
    at doInsert(Code:37:3)

I'd just copied your example code ... and created a Transactions sheet with the correct headers.

It works fine if I copy the built js. code into a .gs file.

**Comment by everythingability** [comment]
Question: (whilst I'm here)... Can I ?

let ss = SpreadsheetApp.openById("whatever-kajsgfkghf3i")
sheetQuery(ss).etc().etc()

...or does it only work with the activeSpreadsheet?

**Comment by everythingability** [comment]
Have you done any code that generates unique Ids and deals with JOINs at all? In any kind of way?

**Comment by bennettscience** [comment]
I think the docs need to be updated. When you import as a library, your identifier is `SheetQuery`, so you create a new query with `SheetQuery.sheetQuery()`. If you're using the library as it's own .gs file, you can call `sheetQuery()` directly.

**Comment by everythingability** [comment]
Oh yeah... silly me. Anyway, thanks.

**Comment by vlucas** [comment]
> I think the docs need to be updated. When you import as a library, your identifier is `SheetQuery`, so you create a new query with `SheetQuery.sheetQuery()`. If you're using the library as it's own .gs file, you can call `sheetQuery()` directly.

Ah, good catch. I will update the docs.
